[package]
name = "esp32motorball"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = "0.10.0"
embassy-futures = "0.1.2"
embassy-net = "0.9.1"
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
embedded-hal-async = "1.0.0"
embedded-io-async = "0.7.0"
esp-alloc = "0.10.0"
esp-backtrace = "0.19.0"
esp-bootloader-esp-idf = "0.5.0"
esp-hal = "1.1.1"
esp-println = "0.17.0"
esp-radio = "0.18.0"
esp-rtos = "0.3.0"
log = "0.4.33"
static_cell = "2.1.1"
